name: CI
on:
  push:
    branches:
      - 'main'
  pull_request:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Build app
        run: |
          npm i
          npm run lint:check
          npm run lint:fix
          npm audit
          npm run build

      - name: Artifact
        run: zip -r bgAddon.zip .

      - name: Upload artifact
        uses: action/upload-artifact@v4
        with:
          name: bgAddon
          path: bgAddon.zip